config/routes.rb
Rails.application.routes.draw do

  root to: 'index#index'

  namespace :auth do
    get ':provider/callback' => :signon
    delete :signout
  end

  resources :corners, only: %i(show new create) do
    resources :battles, only: %i(show new create) do
      resources :entries, only: %i(create destroy) do
        scope(controller: :likes) { post :like, :dislike }
      end
    end

    resources :posts, only: :create

    post 'follow'     => 'followings#create', entity_type: 'Corner'
    delete 'unfollow' => 'followings#destroy', entity_type: 'Corner'
  end
  
  resources :likes, only: :create do
    collection { delete '/' => :destroy }
  end

end

app/models/corner.rb
class Corner < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_many :battles
  has_many :posts

  dragonfly_accessor :logo

  validates :name, presence: true
  validates :slug, presence: true, uniqueness: true

  before_validation :generate_slug

  scope :populated, -> { where('battles_count > 0') }


  def to_param
    slug
  end

  def followers # TODO optimize through joins and cache
    Following.where(entity_type: 'Corner', entity_id: id)
  end

  protected

  def generate_slug
    self.slug = name.to_slug.normalize(transliterations: :russian).to_s unless slug.present?
  end

end

app/controllers/corners_controller.rb
class CornersController < ApplicationController

  def show
    @corner = Corner.find_by!(slug: params[:id])
    @posts = @corner.posts.limit(10)
  end

  def create
    @corner = current_user.corners.create corner_params
    if @corner.persisted?
      Following.create user_id: current_user.id, entity_id: @corner.id, entity_type: Corner
      redirect_to corner_path(@corner)
    else
      Rails.logger.debug @corner.errors.messages
      redirect_to root_path
    end
  end


  protected

  def corner_params
    params.require(:corner).permit(:name, :description, :logo)
  end

end

app/views/corners/new.html.slim
= form_for Corner.new, html: {id: 'corner_form', html: {multipart: true}} do |form|
  h2 Create a new corner
  = form.text_field :name, placeholder: 'Name', autocomplete: 'off'
  = form.text_area :description, rows: 8
  = form.file_field :logo
  = form.submit 'Create'

app/views/corners/show.html.slim
.area
  .units-row
    .unit-20
      #corner-logo style="background-image: url(#{@corner.logo.url})"
    .unit-80




#corner-head
  #corner-face
    - if @corner.logo.present?
      

    - if current_user
      - if current_user.follows? @corner
        = link_to corner_unfollow_path(corner_id: @corner.id), class: 'follow', method: :delete do
          => fa_icon 'star'
          small unfollow
      - else
        = link_to corner_follow_path(corner_id: @corner.id), class: 'follow', method: :post do
          => fa_icon 'star-o'
          small follow

  #corner-basic
    h1 = @corner.name
    hr
    p = simple_format @corner.description

#corner-body
  .grid-left-column
    - if current_user && current_user.in?(@corner.users)
      p = link_to "Start a battle", new_corner_battle_path(@corner)

    - @corner.battles.ordered.each do |battle|
      a.battle href=corner_battle_path(@corner, battle) style="background-image:url(#{ battle.last_entry.image.url rescue nil })"
        div = battle.name
        small style="float: right"
          - if battle.open?
            | #{ distance_of_time_in_words(battle.open_until, Time.now) } left
          - else
            | Concluded
        small #{ battle.entries_count } entries

  .grid-right-column
    h2 Dashboard

    - if can?(:post_to, @corner)
      = form_for [@corner, Post.new] do |f|
        = f.text_area :body, rows: 8, placeholder: 'Post some news'
        = f.submit 'Create a post'

    = render partial: 'partials/timeline', locals: {timeline: @posts}