config/routes.rb
Rails.application.routes.draw do

  root to: 'index#index'

  namespace :auth do
    get ':provider/callback' => :signon
    delete :signout
  end

  resources :corners, only: %i(show new create) do
    resources :battles, only: %i(show new create) do
      resources :entries, only: %i(create destroy) do
        scope(controller: :likes) { post :like, :dislike }
      end
    end

    resources :posts, only: :create

    post 'follow'     => 'followings#create', entity_type: 'Corner'
    delete 'unfollow' => 'followings#destroy', entity_type: 'Corner'
  end
  
  resources :likes, only: :create do
    collection { delete '/' => :destroy }
  end

end

app/views/partials/_corners.html.slim
blocks cols="4"
  - corners.each do |corner|
    .corner-preview
      = link_to corner_path(corner) do
        = image_tag(corner.logo.thumb('60x60#').url, class: 'avatar-medium')
        = corner.name

app/views/partials/_header.html.slim
header
  #auth
    - if current_user
      ul.horizontal
        li: a href="#" Profile
        li => link_to 'Sign out', auth_signout_path, method: :delete
        li = image_tag current_user.avatar, class: 'avatar-tiny'
    - else
      = link_to fa_icon(:vk), '/auth/vkontakte', class: 'auth-provider-icon'
  h1#logo = link_to 'DRAWCLASH', root_path

app/views/partials/_timeline.html.slim
- timeline.each do |post|
  - corner = post.corner
  row.post
    column.logo
      - if corner.logo.present?
        = link_to image_tag(corner.logo.thumb('60x60#').url, class: 'avatar-medium'), corner_path(corner)
    column cols="12"
      h4
        = link_to corner.name.upcase, corner_path(corner)

      p = simple_format post.body
      ul.horizontal.footer
        li = react_component 'DrawClash.Like', liked: post.liked_by?(current_user), likesCount: post.likes.count, url: likes_path(post_id: post.id)
        li #{ time_ago_in_words post.created_at } ago