config/routes.rb
Rails.application.routes.draw do

  root to: 'index#index'

  namespace :auth do
    get ':provider/callback' => :signon
    delete :signout
  end

  resources :corners, only: %i(show new create) do
    resources :battles, only: %i(show new create) do
      resources :entries, only: %i(create destroy) do
        scope(controller: :likes) { post :like, :dislike }
      end
    end

    resources :posts, only: :create

    post 'follow'     => 'followings#create', entity_type: 'Corner'
    delete 'unfollow' => 'followings#destroy', entity_type: 'Corner'
  end
  
  resources :likes, only: :create do
    collection { delete '/' => :destroy }
  end

end

app/models/battle.rb
class Battle < ActiveRecord::Base

  belongs_to :corner, counter_cache: true
  has_many :entries

  validates :name, presence: true

  scope :open, -> { where("open_until > ?", Time.now) }
  scope :ordered, -> { order("(open_until > '#{ Time.now }') DESC").order(created_at: :desc) }

  before_create :set_duration
  after_create :announce


  def open?
    open_until > Time.now
  end

  def last_entry
    entries.order(id: :desc).limit(1).first
  end


  protected

  def set_duration
    self.open_until = 1.week.from_now unless open_until.present?
  end

  def announce
    corner.posts.create body: "New battle #{ name } announced!"
  end

end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController

  ENTRIES_PER_PAGE = 20


  def show
    @battle = Battle.find_by! id: params[:id]
    @entries = @battle.entries.chronologically.limit ENTRIES_PER_PAGE
  end

  def create
    corner = Corner.find_by! slug: params[:corner_id]
    @battle = corner.battles.create name: params[:battle][:name]
    Rails.logger.debug @corner.errors.messages unless @battle.persisted?
    redirect_to corner_path(corner)
  end

end

app/views/battles/new.html.slim
= form_for Battle.new, url: corner_battles_path(corner_id: params[:corner_id]), html: {id: 'battle_form'} do |form|
  h2 Start a new battle
  = form.text_field :name, placeholder: 'Name', autocomplete: 'off'
  = form.submit 'Create'

app/views/battles/show.html.slim
div
  .grid-left-column  
    - if can? :post_entry, @battle
      = form_for Entry.new, url: corner_battle_entries_path(@battle.corner, @battle) do |form|
        = form.file_field :image
        = form.submit "Upload"
  .grid-right-column
    h1.battle-title = @battle.name
    ul.horizontal
      li
        - if @battle.open?
          | #{ distance_of_time_in_words(@battle.open_until, Time.now) } to go
        - else
          | Battle concluded #{ distance_of_time_in_words(@battle.open_until, Time.now) } ago
      li = t 'battle.entries_count', count: @battle.entries_count
  .clear

- if @battle.entries.any?
  .wide = react_component('DrawClash.Grid', {entries: @entries.map {|e| reactize e}})
- else
  .placeholder No entries yet


javascript:
  entriesPath = '#{ corner_battle_entries_path(@battle.corner, @battle) }';